const fs = require('fs');
const path = require('path');
const vm = require('vm');

const files = ['index.html', ...fs.readdirSync('pages').filter(name => name.endsWith('.html')).map(name => path.join('pages', name))];
let count = 0;
for (const file of files) {
  const html = fs.readFileSync(file, 'utf8');
  const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(match => match[1]).filter(code => code.trim());
  scripts.forEach((code, index) => {
    try { new vm.Script(code, {filename: `${file}:inline-${index + 1}`}); }
    catch (error) { throw new Error(`${file} inline script ${index + 1}: ${error.message}`); }
    count += 1;
  });
}
const travel = fs.readFileSync('pages/travel.html', 'utf8');
if (!travel.includes('<option value="">选择一段旅行</option>')) throw new Error('travel reflection must start without a selected trip');
if (!travel.includes("if(select)select.value='';")) throw new Error('travel reflection clear action must reset the selected trip');
if (!travel.includes('data-travel-view="records"') || !travel.includes("showMobileTravelView('records'")) throw new Error('mobile travel must use separate views');
if (travel.includes('id="trip-place" placeholder=') || travel.includes('id="trip-activity" placeholder=') || travel.includes('id="edit-trip-place" placeholder=') || travel.includes('id="edit-trip-activity" placeholder=')) throw new Error('travel destination and theme fields must not show placeholder hints');
if (!travel.includes('← 返回旅行') || !travel.includes('.trip-editor-card,.trip-detail-card{width:100%;height:100%')) throw new Error('travel detail and editor must use full-screen page views');
if (!travel.includes('function removeNewTripPhoto(index)') || !travel.includes('class="new-trip-photo-remove"')) throw new Error('new trip photo previews must support removing individual selections');
if (!travel.includes('reflectionSaveBusy') || !travel.includes('id="reflection-save-button"') || !travel.includes("saveButton.textContent='保存中…'")) throw new Error('travel reflection save must expose and guard its pending state');
if (!travel.includes('function deleteReflection()') || !travel.includes('id="reflection-delete-button"') || !travel.includes('deleted:[tripKey]') || !travel.includes('旅程和照片会保留')) throw new Error('saved travel reflections must support exact-trip deletion without deleting the trip or photos');
if (!travel.includes('function updateReflectionDeleteButton()') || !travel.includes('button.hidden=!exists') || !travel.includes("action:'forget',id")) throw new Error('travel reflection deletion must expose the action only for saved data and forget its memory events');
const heart = fs.readFileSync('pages/heart_hollow.html', 'utf8');
if (!heart.includes('heartReplyBusy') || !heart.includes('id="heart-send"') || !heart.includes("sendButton.textContent='等待回复中…'")) throw new Error('tree hollow reply must expose and guard its pending state');
const home = fs.readFileSync('index.html', 'utf8');
const mobile = fs.readFileSync('core/mobile.js', 'utf8');
const serviceWorker = fs.readFileSync('sw.js', 'utf8');
if (!home.includes('href="pages/heart_hollow.html"') || !home.includes('<span class="tag">树洞</span>')) throw new Error('desktop tree hollow entry must be restored');
if (!home.includes('.stage.has-panorama .spot.orchard{left:15%;top:39%') || !home.includes('.stage.has-panorama .spot.oldtree{left:84%;top:44.5%;width:20%;height:6.5%') || !home.includes('.stage.has-panorama .spot.noticeboard{left:82%;top:51.5%;width:20%;height:6.5%')) throw new Error('mobile noticeboard, orchard, and tree hollow hotspots must stay separate');
if (!home.includes('id="notice-cadence"') || !home.includes('cozy_notice_notes')) throw new Error('notice cadence and reading notes must be present');
if (!home.includes('navigator.geolocation.getCurrentPosition') || !home.includes("'/api/weather'+positionQuery") || !home.includes('location.address||location.city') || home.includes("encodeURIComponent('当前位置')")) throw new Error('owner weather must prefer browser location and display its resolved address');
if (!home.includes("stage.dataset.weatherPending='1';img.src=scenes[last]||scenes.sunny") || home.includes("if(remote){stage.dataset.weatherPending='1';return;}")) throw new Error('home panorama must load immediately instead of waiting for remote weather');
if (!home.includes("openNotice(){\n  openOverlay(") || !home.includes("await syncNoticeFoundResultsFromCloud().catch(()=>[]);")) throw new Error('noticeboard must open before slow cloud refresh work');
if (!home.includes("每周一、周三、周五 08:00 更新 · 往期巡报 ") || !home.includes("report?.id!=='fallback'")) throw new Error('notice cadence must show the fixed schedule and actual archived report count');
if (!mobile.includes("'memory_nook','密阁','private','pages/memory_nook.html'")) throw new Error('mobile private nook must link directly to memory_nook');
if (fs.existsSync('pages/private_wing.html') || serviceWorker.includes('pages/private_wing.html')) throw new Error('legacy private wing transition must be removed');
if (!fs.readFileSync('pages/orchard.html', 'utf8').includes('orchard_field.webp')) throw new Error('orchard must use the optimized WebP background');
const orchard = fs.readFileSync('pages/orchard.html', 'utf8');
if (!orchard.includes('.plot:nth-child(1){left:49%;top:42.5%') || !orchard.includes('.plot:nth-child(5){left:48%;top:65%') || !orchard.includes('.plot-copy{left:3%;right:3%;bottom:32px}')) throw new Error('mobile orchard plots must align with the illustrated soil beds');
if (!orchard.includes("slice(0,-1).slice(-8)") || !orchard.includes("current_topic_id:chat?.topicId||''")) throw new Error('orchard chat must send prior turns separately from the current question');
if (!(orchard.indexOf('id="orchard-chat-thread"') < orchard.indexOf('class="chat-examples" aria-label="提问模板"') && orchard.indexOf('class="chat-examples" aria-label="提问模板"') < orchard.indexOf('id="seed-input"'))) throw new Error('orchard prompt templates must sit directly above the composer');
if (!orchard.includes('function renderOrchardChat(pending=orchardBusy)') || !orchard.includes('正在回复') || !orchard.includes("aria-busy',String(Boolean(pending))")) throw new Error('orchard chat must keep a visible reply state across sync renders');
if (!orchard.includes('openEmptyPlotPanel()') || !orchard.includes('这块空地的知识专题')) throw new Error('empty orchard plots must open a knowledge-topic empty state');
if (!orchard.includes('fingerprint===knowledgeRenderFingerprint') || !orchard.includes("details[open][data-topic-id]") || orchard.includes("open=first?' open':''")) throw new Error('knowledge topics must preserve manual collapse state across sync renders');
if (!orchard.includes('function syncLearningSourcesToTopics()') || !orchard.includes("readJson('cozy_blackboard_answers',[])") || !orchard.includes("readJson('cozy_notice_notes',[])")) throw new Error('orchard must import blackboard learning and notice notes into knowledge topics');
if (!orchard.includes("sourceId,kind:'answer_review'") || !orchard.includes("kind:'reading_note'") || !orchard.includes("entry.source!==spec.source")) throw new Error('learning-source imports must use stable source ids and reconcile removed source entries');
if ((orchard.match(/syncLearningSourcesToTopics\(\)/g)||[]).length < 3) throw new Error('learning-source imports must run on initial load and cloud state sync');
if (orchard.includes('(?<=') || orchard.includes('(?<!')) throw new Error('orchard must avoid regex lookbehind for older mobile browsers');
if (!home.includes('String(item.awarded??0)') || !home.includes('String(item.max??25)')) throw new Error('blackboard must display explicit zero scores');
if (!home.includes('grade-blackboard-answer') || !home.includes('function normalizeBlackboardReview') || !home.includes('得分与学习建议') || !home.includes('怎样提高') || !home.includes('五档锚点') || !home.includes('题意理解与核心判断')) throw new Error('anchored tutoring-style blackboard grading must be wired into the UI');
if (!home.includes('阿栗的完整面试回答') || !home.includes('不是要点清单') || !home.includes('评分参考要点') || !home.includes('用于核分，不是完整答案') || !home.includes('结合你的回答给的建议') || !home.includes('personalized_revision')) throw new Error('blackboard must separate scoring points, independent ideal answer, personalized advice, and interview revision');
if (!home.includes('大白话学会这题') || !home.includes('真正要记住的点') || !home.includes('next_question_ideal_answer') || !home.includes('查看阿栗答案')) throw new Error('blackboard must teach the answer in plain language and include a complete answer for next practice');
if (home.includes('<h4>阿栗帮答</h4>') || home.includes('<h4>AI 修改建议</h4>')) throw new Error('legacy generic grading sections must not remain in the result UI');
if (!home.includes("loading:requiresFreshQuestion") || !home.includes("/api/blackboard/today?date=") || !home.includes("重新加载今日题目")) throw new Error('online blackboard must wait for a fresh dated question and expose retry');
if (!home.includes('手机与云端的连接在批改完成前中断') || !home.includes('模型本次响应超时')) throw new Error('blackboard grading failures must be readable on mobile');
if (!home.includes("今日题目 · '+escapeNotice(q.date||localCalendarDate())")) throw new Error('blackboard must show the active question date');
if (!home.includes("setBlackboardHistoryFilter(\\'category\\')") || !home.includes('全部按最近作答时间排列') || !home.includes('function blackboardHistoryTimestamp')) throw new Error('blackboard history must support chronological, category, and starred views');
if (!home.includes("regrading:false") || !home.includes("if(!answer||!q||state.regrading)return") || !home.includes("busy?'核分中…':'重新核分'")) throw new Error('blackboard regrade state must survive mode rerenders and block duplicate requests');
if (!home.includes("syncLocalState(['cozy_blackboard_answers'])") || !home.includes('function blackboardReviewComplete(review)') || !home.includes("gradingComplete?'本题已批改':'答案已提交'") || !home.includes('updatedAt:new Date().toISOString()')) throw new Error('blackboard must sync cloud answers and distinguish submitted answers from completed grading');
if (!home.includes('data-notice-view="current"') || !home.includes("showNoticeView('current',document.querySelector('[data-notice-view=\"current\"]'))")) throw new Error('noticeboard must always open on the latest report view');
if (!home.includes("window.BB_STATE&&window.BB_STATE.submitting?'批改中…'") || !home.includes('state.helperPending') || !home.includes('等待回复中…')) throw new Error('blackboard grading and helper waits must survive mode rerenders');
if (!home.includes('function blackboardQuestionIsDuplicate') || !home.includes('连续三次都生成了做过或高度相似的题目')) throw new Error('blackboard refresh must reject answered and highly similar questions');
if (!home.includes('openBlackboardRelatedNotice()') || !home.includes("q.related_notice&&q.related_notice.title")) throw new Error('blackboard related-news action must be conditional');
if (!home.includes('function noticePublishedLabel(item)') || !home.includes('item.published_at')) throw new Error('notice cards must use concrete publication dates with a weekly fallback');
if (!home.includes('function noticeItemDisplayable(item)') || !home.includes("cozyApi('/api/status', undefined, 15000)")) throw new Error('noticeboard must hide known bad cards and tolerate cloud cold starts');
if (!home.includes('prepareNoticeFoundResults()') || !home.includes('acceptNoticeFollowupResponse') || !home.includes('cozy_notice_found_seen_v1') || !home.includes('来自留言：“') || !home.includes('noticeManualRefreshPending')) throw new Error('found notice items must identify their request, survive a KV-limit response, and disappear per device after first display');
if (!home.includes("cache:'no-store',credentials:'same-origin'")) throw new Error('API GET requests must bypass stale mobile caches');
if (!serviceWorker.includes("url.pathname.includes('/assets/')")) throw new Error('static assets must use the cache-first path');
if (!serviceWorker.includes("cozy-shell-v24") || !fs.readFileSync('core/pwa.js','utf8').includes("sw.js?v=24") || !fs.readFileSync('core/pwa.js','utf8').includes("updateViaCache:'none'") || !fs.readFileSync('core/pwa.js','utf8').includes("controllerchange")) throw new Error('PWA shell updates must bypass stale service worker cache and reload after takeover');
if (!home.includes("return remote?[]:[NOTICE_REPORT_FALLBACK()]") || !home.includes('页面不会再显示旧版占位巡报')) throw new Error('remote noticeboard must not show bundled fallback reports');
if (!home.includes('async function openNotice(){') || !home.includes('await CORE_READY;')) throw new Error('noticeboard must wait for cloud core data before rendering');
if (!home.includes('refreshNoticeReportsFromCloud()') || !home.includes("cache:'no-store',credentials:'same-origin'")) throw new Error('noticeboard must revalidate cloud reports when opened');
if (!home.includes('产品经理关注点') || !home.includes('data-product-tip=') || !home.includes("product_tip: item.product_tip")) throw new Error('notice cards must render and persist optional Chinese product tips');
if (!home.includes("'本次更新未完成：'+error.message") || !home.includes("'国内 '+coverage.domestic+' 条、海外 '+coverage.international")) throw new Error('manual notice refresh must report precise failures and domestic/international coverage');
if (!home.includes('Promise.all(Object.entries(files).map')) throw new Error('core cloud data must load in parallel');
if (!home.includes('async function openToolbox(){') || !home.includes("cozyApi('/api/state',undefined,6000)")) throw new Error('toolbox must refresh cloud state when opened');
if (!home.includes('comparableButlerState(localButlerState())') || home.includes('applyButlerServerState(data.state,true);\n  await pushButlerState();')) throw new Error('opening the noticeboard must not rewrite unchanged butler state');
if (!home.includes('>加入工具箱</button>') || !home.includes('source,instruction:')) throw new Error('notice tool import must send the existing report context');
if (home.includes('removeCourtyardScene(') || home.includes('从小院照片合集中移除')) throw new Error('courtyard background collection must not expose deletion controls');
if (!home.includes('.photo-album-cover img{position:static;width:100%;height:100%;object-fit:contain')) throw new Error('photo album covers must preserve source aspect ratios');
if (!home.includes('function renamePhotoAlbum(albumId)') || !home.includes('>重命名</button>') || !home.includes("album.source==='aggregate'")) throw new Error('editable photo albums must support renaming without changing the aggregate collection');
console.log(`html syntax test ok: ${files.length} pages; ${count} inline scripts`);
